import {
  ApertureIcon,
  BoxesIcon,
  BugIcon,
  ContrastIcon,
  FolderOpenIcon,
  FrameIcon,
  GitBranchIcon,
  LightbulbIcon,
  MonitorIcon,
  PaletteIcon,
  SparklesIcon,
  SunIcon,
  WavesIcon,
} from "lucide-react";

import type { CameraMode, CameraSettingGroup, PipelineSection } from "@/lib/pipeline-types";

export const cameraModes: CameraMode[] = [
  {
    label: "Pinhole",
    description: "single origin perspective rays",
    settingGroups: [
      {
        title: "Projection",
        settings: [
          {
            id: "pinhole-fov",
            label: "vertical field of view",
            control: "number",
            defaultValue: 34,
            min: 1,
            max: 179,
            step: 1,
            suffix: "deg",
          },
          {
            id: "pinhole-aspect",
            label: "aspect ratio",
            control: "select",
            defaultValue: "16:9",
            options: ["1:1", "4:3", "16:9", "21:9"],
          },
          {
            id: "pinhole-near",
            label: "near clip",
            control: "number",
            defaultValue: 0.1,
            min: 0.01,
            step: 0.01,
          },
          {
            id: "pinhole-far",
            label: "far clip",
            control: "number",
            defaultValue: 100,
            min: 1,
            step: 1,
          },
        ],
      },
      {
        title: "Pose",
        settings: [
          {
            id: "pinhole-position",
            label: "position",
            control: "text",
            defaultValue: "3.1, 2.1, 5.7",
          },
          {
            id: "pinhole-target",
            label: "look target",
            control: "text",
            defaultValue: "0, 0.85, 0",
          },
          {
            id: "pinhole-up",
            label: "up vector",
            control: "select",
            defaultValue: "+Y",
            options: ["+Y", "+Z"],
          },
        ],
      },
    ],
  },
  {
    label: "Orthographic",
    description: "parallel rays with fixed scale",
    settingGroups: [
      {
        title: "Projection",
        settings: [
          {
            id: "ortho-scale",
            label: "orthographic scale",
            control: "number",
            defaultValue: 4,
            min: 0.1,
            step: 0.1,
          },
          {
            id: "ortho-aspect",
            label: "aspect ratio",
            control: "select",
            defaultValue: "16:9",
            options: ["1:1", "4:3", "16:9", "21:9"],
          },
          {
            id: "ortho-near",
            label: "near clip",
            control: "number",
            defaultValue: 0.1,
            min: 0.01,
            step: 0.01,
          },
          {
            id: "ortho-far",
            label: "far clip",
            control: "number",
            defaultValue: 100,
            min: 1,
            step: 1,
          },
        ],
      },
      {
        title: "Pose",
        settings: [
          {
            id: "ortho-position",
            label: "position",
            control: "text",
            defaultValue: "3.1, 2.1, 5.7",
          },
          {
            id: "ortho-direction",
            label: "look direction",
            control: "select",
            defaultValue: "-Z",
            options: ["-Z", "+Z", "-X", "+X", "-Y", "+Y"],
          },
          {
            id: "ortho-up",
            label: "up vector",
            control: "select",
            defaultValue: "+Y",
            options: ["+Y", "+Z"],
          },
        ],
      },
    ],
  },
  {
    label: "Thin lens",
    description: "perspective with depth of field",
    settingGroups: [
      {
        title: "Projection",
        settings: [
          {
            id: "thin-fov",
            label: "vertical field of view",
            control: "number",
            defaultValue: 34,
            min: 1,
            max: 179,
            step: 1,
            suffix: "deg",
          },
          {
            id: "thin-focal-length",
            label: "focal length",
            control: "number",
            defaultValue: 50,
            min: 1,
            step: 1,
            suffix: "mm",
          },
          {
            id: "thin-sensor-fit",
            label: "sensor fit",
            control: "select",
            defaultValue: "35mm full frame",
            options: ["35mm full frame", "APS-C", "Micro 4/3", "custom"],
          },
        ],
      },
      {
        title: "Lens",
        settings: [
          {
            id: "thin-aperture-radius",
            label: "aperture radius",
            control: "number",
            defaultValue: 0.04,
            min: 0,
            step: 0.01,
          },
          {
            id: "thin-focus-distance",
            label: "focus distance",
            control: "number",
            defaultValue: 5,
            min: 0.1,
            step: 0.1,
            suffix: "m",
          },
          {
            id: "thin-aperture-blades",
            label: "aperture blades",
            control: "number",
            defaultValue: 7,
            min: 3,
            max: 16,
            step: 1,
          },
          {
            id: "thin-bokeh-rotation",
            label: "bokeh rotation",
            control: "number",
            defaultValue: 0,
            min: 0,
            max: 360,
            step: 1,
            suffix: "deg",
          },
        ],
      },
    ],
  },
  {
    label: "Fisheye",
    description: "wide-angle curved projection",
    settingGroups: [
      {
        title: "Projection",
        settings: [
          {
            id: "fisheye-mapping",
            label: "fisheye mapping",
            control: "select",
            defaultValue: "equidistant",
            options: ["equidistant", "equisolid", "orthographic", "stereographic"],
          },
          {
            id: "fisheye-fov",
            label: "field of view",
            control: "number",
            defaultValue: 180,
            min: 1,
            max: 360,
            step: 1,
            suffix: "deg",
          },
          { id: "fisheye-crop", label: "image circle crop", control: "toggle", defaultValue: true },
        ],
      },
      {
        title: "Pose",
        settings: [
          { id: "fisheye-position", label: "position", control: "text", defaultValue: "0, 1.5, 0" },
          {
            id: "fisheye-direction",
            label: "look direction",
            control: "select",
            defaultValue: "-Z",
            options: ["-Z", "+Z", "-X", "+X"],
          },
          {
            id: "fisheye-roll",
            label: "roll",
            control: "number",
            defaultValue: 0,
            min: -180,
            max: 180,
            step: 1,
            suffix: "deg",
          },
        ],
      },
    ],
  },
  {
    label: "Equirectangular",
    description: "lat-long panorama rays",
    settingGroups: [
      {
        title: "Coverage",
        settings: [
          {
            id: "eq-horizontal",
            label: "horizontal coverage",
            control: "number",
            defaultValue: 360,
            min: 1,
            max: 360,
            step: 1,
            suffix: "deg",
          },
          {
            id: "eq-vertical",
            label: "vertical coverage",
            control: "number",
            defaultValue: 180,
            min: 1,
            max: 180,
            step: 1,
            suffix: "deg",
          },
          {
            id: "eq-seam",
            label: "seam longitude",
            control: "number",
            defaultValue: 0,
            min: -180,
            max: 180,
            step: 1,
            suffix: "deg",
          },
        ],
      },
      {
        title: "Pose",
        settings: [
          { id: "eq-position", label: "position", control: "text", defaultValue: "0, 1.5, 0" },
          {
            id: "eq-heading",
            label: "heading",
            control: "number",
            defaultValue: 0,
            min: -180,
            max: 180,
            step: 1,
            suffix: "deg",
          },
          {
            id: "eq-pitch",
            label: "pitch",
            control: "number",
            defaultValue: 0,
            min: -90,
            max: 90,
            step: 1,
            suffix: "deg",
          },
        ],
      },
    ],
  },
  {
    label: "Cubemap",
    description: "six square face cameras",
    settingGroups: [
      {
        title: "Faces",
        settings: [
          {
            id: "cube-resolution",
            label: "face resolution",
            control: "select",
            defaultValue: "1024",
            options: ["512", "1024", "2048", "4096"],
          },
          {
            id: "cube-face-order",
            label: "face order",
            control: "select",
            defaultValue: "+X -X +Y -Y +Z -Z",
            options: ["+X -X +Y -Y +Z -Z", "+X -X +Z -Z +Y -Y"],
          },
          {
            id: "cube-seam-fixup",
            label: "edge seam fixup",
            control: "toggle",
            defaultValue: true,
          },
        ],
      },
      {
        title: "Pose",
        settings: [
          { id: "cube-position", label: "position", control: "text", defaultValue: "0, 1.5, 0" },
          {
            id: "cube-basis",
            label: "orientation basis",
            control: "select",
            defaultValue: "OpenGL",
            options: ["OpenGL", "DirectX", "custom"],
          },
        ],
      },
    ],
  },
  {
    label: "Stereo / VR",
    description: "paired eye projections",
    settingGroups: [
      {
        title: "Rig",
        settings: [
          {
            id: "stereo-eye-separation",
            label: "eye separation",
            control: "number",
            defaultValue: 0.064,
            min: 0,
            step: 0.001,
            suffix: "m",
          },
          {
            id: "stereo-convergence",
            label: "convergence distance",
            control: "number",
            defaultValue: 10,
            min: 0.1,
            step: 0.1,
            suffix: "m",
          },
          {
            id: "stereo-projection",
            label: "per-eye projection",
            control: "select",
            defaultValue: "asymmetric frustum",
            options: ["asymmetric frustum", "parallel", "toe-in"],
          },
        ],
      },
      {
        title: "Display",
        settings: [
          {
            id: "stereo-distortion",
            label: "lens distortion profile",
            control: "select",
            defaultValue: "none",
            options: ["none", "OpenXR", "custom"],
          },
          {
            id: "stereo-ipd-offset",
            label: "interpupillary offset",
            control: "number",
            defaultValue: 0,
            step: 0.001,
            suffix: "m",
          },
          {
            id: "stereo-layout",
            label: "view layout",
            control: "select",
            defaultValue: "side-by-side",
            options: ["side-by-side", "top-bottom", "per-eye targets"],
          },
        ],
      },
    ],
  },
  {
    label: "Oblique",
    description: "orthographic with projection shear",
    settingGroups: [
      {
        title: "Projection",
        settings: [
          {
            id: "oblique-scale",
            label: "orthographic scale",
            control: "number",
            defaultValue: 4,
            min: 0.1,
            step: 0.1,
          },
          {
            id: "oblique-shear",
            label: "shear angle",
            control: "number",
            defaultValue: 45,
            min: 0,
            max: 89,
            step: 1,
            suffix: "deg",
          },
          {
            id: "oblique-axis",
            label: "receding axis",
            control: "select",
            defaultValue: "+X",
            options: ["+X", "-X", "+Y", "-Y"],
          },
        ],
      },
      {
        title: "Clipping",
        settings: [
          {
            id: "oblique-near",
            label: "near clip",
            control: "number",
            defaultValue: 0.1,
            min: 0.01,
            step: 0.01,
          },
          {
            id: "oblique-far",
            label: "far clip",
            control: "number",
            defaultValue: 100,
            min: 1,
            step: 1,
          },
        ],
      },
    ],
  },
  {
    label: "Isometric",
    description: "fixed equal-axis orthographic",
    settingGroups: [
      {
        title: "Projection",
        settings: [
          {
            id: "iso-scale",
            label: "orthographic scale",
            control: "number",
            defaultValue: 4,
            min: 0.1,
            step: 0.1,
          },
          {
            id: "iso-orientation",
            label: "isometric orientation",
            control: "select",
            defaultValue: "standard",
            options: ["standard", "left", "right", "custom"],
          },
          { id: "iso-snap", label: "snap rotation", control: "toggle", defaultValue: true },
        ],
      },
      {
        title: "Clipping",
        settings: [
          {
            id: "iso-near",
            label: "near clip",
            control: "number",
            defaultValue: 0.1,
            min: 0.01,
            step: 0.01,
          },
          {
            id: "iso-far",
            label: "far clip",
            control: "number",
            defaultValue: 100,
            min: 1,
            step: 1,
          },
        ],
      },
    ],
  },
  {
    label: "Motion blur",
    description: "camera rays sampled across time",
    settingGroups: [
      {
        title: "Shutter",
        settings: [
          {
            id: "motion-shutter-open",
            label: "shutter open",
            control: "number",
            defaultValue: 0,
            min: 0,
            step: 0.01,
          },
          {
            id: "motion-shutter-close",
            label: "shutter close",
            control: "number",
            defaultValue: 0.5,
            min: 0,
            step: 0.01,
          },
          {
            id: "motion-time-distribution",
            label: "sample time distribution",
            control: "select",
            defaultValue: "uniform",
            options: ["uniform", "center-weighted", "custom curve"],
          },
        ],
      },
      {
        title: "Motion",
        settings: [
          {
            id: "motion-interpolation",
            label: "transform interpolation",
            control: "select",
            defaultValue: "linear",
            options: ["linear", "cubic", "step"],
          },
          {
            id: "motion-rolling-direction",
            label: "rolling shutter direction",
            control: "select",
            defaultValue: "none",
            options: ["none", "top to bottom", "left to right"],
          },
          {
            id: "motion-rolling-duration",
            label: "rolling shutter duration",
            control: "number",
            defaultValue: 0,
            min: 0,
            step: 0.01,
          },
        ],
      },
    ],
  },
  {
    label: "Physical",
    description: "sensor and exposure model",
    settingGroups: [
      {
        title: "Body",
        settings: [
          {
            id: "physical-focal-length",
            label: "focal length",
            control: "number",
            defaultValue: 50,
            min: 1,
            step: 1,
            suffix: "mm",
          },
          {
            id: "physical-sensor-size",
            label: "sensor size",
            control: "select",
            defaultValue: "36 x 24 mm",
            options: ["36 x 24 mm", "24 x 16 mm", "17.3 x 13 mm", "custom"],
          },
          {
            id: "physical-film-gate",
            label: "film gate",
            control: "select",
            defaultValue: "horizontal",
            options: ["horizontal", "vertical", "fill", "overscan"],
          },
          {
            id: "physical-crop-factor",
            label: "crop factor",
            control: "number",
            defaultValue: 1,
            min: 0.1,
            step: 0.1,
          },
        ],
      },
      {
        title: "Exposure",
        settings: [
          {
            id: "physical-fstop",
            label: "f-stop",
            control: "number",
            defaultValue: 2.8,
            min: 0.7,
            step: 0.1,
          },
          {
            id: "physical-shutter-speed",
            label: "shutter speed",
            control: "select",
            defaultValue: "1/125",
            options: ["1/30", "1/60", "1/125", "1/250", "1/500"],
          },
          {
            id: "physical-iso",
            label: "ISO-like exposure",
            control: "number",
            defaultValue: 100,
            min: 25,
            step: 25,
          },
        ],
      },
    ],
  },
];

export const pipelineSections: PipelineSection[] = [
  {
    id: "camera",
    title: "Camera",
    icon: ApertureIcon,
    activeLabel: "Camera type",
    selectOptions: cameraModes.map((mode) => mode.label),
    groups: [],
    minimum: ["Pinhole", "Orthographic", "Thin lens"],
  },
  {
    id: "geometry",
    title: "Geometry",
    icon: BoxesIcon,
    activeLabel: "Primary geometry",
    selectOptions: [
      "sphere",
      "plane",
      "triangle",
      "quad",
      "box",
      "capsule",
      "cylinder",
      "cone",
      "disk",
      "torus",
    ],
    groups: [
      {
        title: "Primitive geometry",
        options: [
          "sphere",
          "plane",
          "triangle",
          "quad",
          "box",
          "capsule",
          "cylinder",
          "cone",
          "disk",
          "torus",
        ],
      },
      {
        title: "Mesh geometry",
        options: [
          "triangle mesh",
          "indexed triangle mesh",
          "instanced mesh",
          "skinned mesh",
          "displacement mesh",
          "subdivision mesh",
        ],
      },
      {
        title: "Procedural geometry",
        options: [
          "signed distance fields",
          "metaballs",
          "fractals",
          "heightfields",
          "voxels",
          "implicit surfaces",
          "constructive solid geometry",
        ],
      },
      {
        title: "Scene composition",
        options: [
          "static objects",
          "dynamic objects",
          "instanced objects",
          "animated objects",
          "emissive objects",
          "invisible-to-camera objects",
          "shadow-only objects",
        ],
      },
    ],
    minimum: ["sphere", "triangle", "triangle mesh", "instanced mesh"],
  },
  {
    id: "material",
    title: "Material",
    icon: PaletteIcon,
    activeLabel: "Default material",
    selectOptions: [
      "diffuse / Lambertian",
      "metal",
      "dielectric / glass",
      "emissive",
      "glossy",
      "rough conductor",
      "rough dielectric",
      "Disney principled",
      "clearcoat",
      "subsurface",
      "anisotropic",
      "translucent",
      "volume material",
      "procedural material",
    ],
    groups: [
      {
        title: "Material library",
        options: [
          "diffuse / Lambertian",
          "metal",
          "dielectric / glass",
          "emissive",
          "glossy",
          "rough conductor",
          "rough dielectric",
          "Disney principled",
          "clearcoat",
          "subsurface",
          "anisotropic",
          "translucent",
          "volume material",
          "procedural material",
        ],
      },
    ],
    minimum: ["diffuse / Lambertian", "metal", "dielectric / glass", "emissive"],
  },
  {
    id: "light",
    title: "Light",
    icon: LightbulbIcon,
    activeLabel: "Primary light",
    selectOptions: [
      "point light",
      "directional light",
      "spot light",
      "area light",
      "sphere light",
      "quad light",
      "triangle mesh light",
      "environment map",
      "sky model",
      "emissive geometry",
    ],
    groups: [
      {
        title: "Light library",
        options: [
          "point light",
          "directional light",
          "spot light",
          "area light",
          "sphere light",
          "quad light",
          "triangle mesh light",
          "environment map",
          "sky model",
          "emissive geometry",
        ],
      },
    ],
    minimum: ["emissive geometry", "quad light", "environment map"],
  },
  {
    id: "scene-loader",
    title: "Scene Loader",
    icon: FolderOpenIcon,
    activeLabel: "Loader",
    selectOptions: [
      "hardcoded scene",
      "JSON scene",
      "glTF",
      "OBJ",
      "procedural scene",
      "editor-authored scene",
      "benchmark scene",
    ],
    groups: [
      {
        title: "Sources",
        options: [
          "hardcoded scene",
          "JSON scene",
          "glTF",
          "OBJ",
          "procedural scene",
          "editor-authored scene",
          "benchmark scene",
        ],
      },
    ],
    minimum: ["hardcoded scene", "JSON scene", "glTF"],
  },
  {
    id: "tracer",
    title: "Tracer",
    icon: GitBranchIcon,
    activeLabel: "Trace backend",
    selectOptions: [
      "brute force",
      "uniform grid",
      "BVH",
      "wide BVH",
      "two-level BVH",
      "KD-tree",
      "octree",
      "bounding sphere hierarchy",
      "SDF ray marcher",
      "voxel DDA tracer",
      "heightfield tracer",
      "hardware ray tracing backend",
      "hybrid raster + ray query tracer",
    ],
    groups: [
      {
        title: "Basic tracers",
        options: [
          "brute force",
          "uniform grid",
          "BVH",
          "wide BVH",
          "two-level BVH",
          "KD-tree",
          "octree",
          "bounding sphere hierarchy",
        ],
      },
      {
        title: "Specialized tracers",
        options: [
          "SDF ray marcher",
          "voxel DDA tracer",
          "heightfield tracer",
          "hardware ray tracing backend",
          "hybrid raster + ray query tracer",
        ],
      },
      {
        title: "Debug tracers",
        options: [
          "first-hit only",
          "any-hit / shadow ray only",
          "closest-hit",
          "intersection count visualizer",
          "BVH depth visualizer",
          "traversal heatmap",
        ],
      },
    ],
    minimum: ["brute force", "BVH", "SDF ray marcher"],
  },
  {
    id: "sampler",
    title: "Sampler",
    icon: WavesIcon,
    activeLabel: "Pixel sampler",
    selectOptions: [
      "white noise",
      "frame-indexed white noise",
      "hash-based RNG",
      "PCG",
      "XorShift",
      "Wang hash",
      "stratified sampling",
      "jittered grid",
      "Latin hypercube",
      "Halton",
      "Hammersley",
      "Sobol",
      "Owen-scrambled Sobol",
      "blue noise",
      "tiled blue noise",
      "spatiotemporal blue noise",
      "Bayer matrix",
      "interleaved gradient noise",
    ],
    groups: [
      {
        title: "Basic samplers",
        options: [
          "white noise",
          "frame-indexed white noise",
          "hash-based RNG",
          "PCG",
          "XorShift",
          "Wang hash",
        ],
      },
      {
        title: "Structured samplers",
        options: [
          "stratified sampling",
          "jittered grid",
          "Latin hypercube",
          "Halton",
          "Hammersley",
          "Sobol",
          "Owen-scrambled Sobol",
        ],
      },
      {
        title: "Image-space samplers",
        options: [
          "blue noise",
          "tiled blue noise",
          "spatiotemporal blue noise",
          "Bayer matrix",
          "interleaved gradient noise",
        ],
      },
      {
        title: "Domain-specific samplers",
        options: [
          "hemisphere uniform",
          "hemisphere cosine-weighted",
          "sphere sampling",
          "disk sampling",
          "cone sampling",
          "GGX sampling",
          "light sampling",
          "environment map sampling",
          "triangle area sampling",
        ],
      },
    ],
    minimum: [
      "white noise",
      "blue noise",
      "hemisphere cosine-weighted",
      "GGX sampling",
      "light sampling",
    ],
  },
  {
    id: "integrator",
    title: "Integrator",
    icon: SunIcon,
    activeLabel: "Integrator",
    selectOptions: [
      "solid color",
      "normal view",
      "depth view",
      "albedo view",
      "UV view",
      "material ID view",
      "primitive ID view",
      "world position view",
      "bounce count view",
      "ray distance view",
      "heatmap view",
      "ambient only",
      "direct lighting",
      "direct lighting with shadows",
      "ambient occlusion",
      "path tracing",
      "path tracing with next-event estimation",
      "path tracing with multiple importance sampling",
      "bidirectional path tracing",
      "volumetric path tracing",
      "photon mapping",
      "ReSTIR direct lighting",
      "ReSTIR global illumination",
    ],
    groups: [
      {
        title: "Debug integrators",
        options: [
          "solid color",
          "normal view",
          "depth view",
          "albedo view",
          "UV view",
          "material ID view",
          "primitive ID view",
          "world position view",
          "bounce count view",
          "ray distance view",
          "heatmap view",
        ],
      },
      {
        title: "Lighting integrators",
        options: [
          "ambient only",
          "direct lighting",
          "direct lighting with shadows",
          "ambient occlusion",
          "path tracing",
          "path tracing with next-event estimation",
          "path tracing with multiple importance sampling",
          "bidirectional path tracing",
          "volumetric path tracing",
          "photon mapping",
          "ReSTIR direct lighting",
          "ReSTIR global illumination",
        ],
      },
      {
        title: "Special effects integrators",
        options: [
          "reflection-only",
          "refraction-only",
          "caustics experiment",
          "participating media",
          "subsurface scattering",
          "spectral rendering",
          "toon/path hybrid",
        ],
      },
    ],
    minimum: [
      "normal view",
      "depth view",
      "direct lighting",
      "path tracing",
      "path tracing with next-event estimation",
    ],
  },
  {
    id: "denoiser",
    title: "Denoiser",
    icon: SparklesIcon,
    activeLabel: "Denoiser",
    selectOptions: [
      "none",
      "simple temporal accumulation",
      "exponential moving average",
      "accumulation with reset",
      "accumulation with variance estimate",
      "box blur",
      "Gaussian blur",
      "bilateral filter",
      "a-trous wavelet filter",
      "edge-aware filter",
      "normal/depth-aware filter",
      "temporal reprojection",
      "temporal anti-aliasing",
      "history clamping",
      "variance-guided temporal filtering",
      "SVGF",
      "A-SVGF",
      "ReBLUR-style denoiser",
      "neural denoiser",
      "path-space denoiser",
    ],
    groups: [
      {
        title: "No-op / accumulation",
        options: [
          "none",
          "simple temporal accumulation",
          "exponential moving average",
          "accumulation with reset",
          "accumulation with variance estimate",
        ],
      },
      {
        title: "Spatial filters",
        options: [
          "box blur",
          "Gaussian blur",
          "bilateral filter",
          "a-trous wavelet filter",
          "edge-aware filter",
          "normal/depth-aware filter",
        ],
      },
      {
        title: "Temporal filters",
        options: [
          "temporal reprojection",
          "temporal anti-aliasing",
          "history clamping",
          "variance-guided temporal filtering",
        ],
      },
      {
        title: "Advanced denoisers",
        options: [
          "SVGF",
          "A-SVGF",
          "ReBLUR-style denoiser",
          "neural denoiser",
          "path-space denoiser",
        ],
      },
      {
        title: "Auxiliary buffers",
        options: [
          "depth",
          "normal",
          "albedo",
          "motion vectors",
          "material ID",
          "roughness",
          "variance",
          "sample count",
        ],
      },
    ],
    minimum: ["none", "simple temporal accumulation", "bilateral filter", "SVGF"],
  },
  {
    id: "tonemapper",
    title: "Tonemapper",
    icon: ContrastIcon,
    activeLabel: "Curve",
    selectOptions: [
      "linear",
      "clamp",
      "Reinhard",
      "extended Reinhard",
      "exposure only",
      "gamma correction",
      "ACES approximation",
      "Uncharted 2 filmic",
      "Hable",
      "AgX",
      "Khronos PBR Neutral",
      "custom filmic curve",
    ],
    groups: [
      {
        title: "Basic tonemappers",
        options: [
          "linear",
          "clamp",
          "Reinhard",
          "extended Reinhard",
          "exposure only",
          "gamma correction",
        ],
      },
      {
        title: "Filmic tonemappers",
        options: [
          "ACES approximation",
          "Uncharted 2 filmic",
          "Hable",
          "AgX",
          "Khronos PBR Neutral",
          "custom filmic curve",
        ],
      },
      {
        title: "Color pipeline",
        options: [
          "exposure",
          "white balance",
          "contrast",
          "saturation",
          "gamma",
          "color grading LUT",
          "bloom combine",
          "vignette",
        ],
      },
      {
        title: "Output formats",
        options: ["sRGB", "linear RGB", "HDR10-ish output", "display P3", "Rec.709"],
      },
    ],
    minimum: ["linear", "Reinhard", "ACES approximation", "exposure", "gamma correction"],
  },
  {
    id: "render-target",
    title: "Render Target",
    icon: FrameIcon,
    activeLabel: "Target mode",
    selectOptions: [
      "full resolution",
      "half resolution",
      "tiled rendering",
      "progressive rendering",
      "checkerboard rendering",
      "adaptive resolution",
      "fixed sample budget",
    ],
    groups: [
      {
        title: "Target modes",
        options: [
          "full resolution",
          "half resolution",
          "tiled rendering",
          "progressive rendering",
          "checkerboard rendering",
          "adaptive resolution",
          "fixed sample budget",
        ],
      },
    ],
    minimum: ["full resolution", "progressive rendering"],
  },
  {
    id: "display",
    title: "Display",
    icon: MonitorIcon,
    activeLabel: "Viewport",
    selectOptions: ["canvas viewport", "fullscreen preview", "split compare", "histogram overlay"],
    groups: [
      {
        title: "Viewport overlays",
        options: [
          "sample count",
          "frame time",
          "exposure readout",
          "pixel inspector",
          "false-color legend",
        ],
      },
    ],
    minimum: ["canvas viewport", "sample count"],
  },
  {
    id: "debug-views",
    title: "Debug Views",
    icon: BugIcon,
    activeLabel: "Debug view",
    selectOptions: [
      "none",
      "normal view",
      "depth view",
      "albedo view",
      "material ID view",
      "primitive ID view",
      "BVH depth visualizer",
      "traversal heatmap",
    ],
    groups: [
      {
        title: "Inspection overlays",
        options: [
          "normal view",
          "depth view",
          "albedo view",
          "material ID view",
          "primitive ID view",
          "world position view",
          "bounce count view",
          "ray distance view",
          "BVH depth visualizer",
          "traversal heatmap",
        ],
      },
    ],
    minimum: ["none", "normal view", "depth view"],
  },
];

export const pipelineSectionSettingGroups: Record<string, CameraSettingGroup[]> = {
  geometry: [
    {
      title: "Placement",
      settings: [
        { id: "geometry-transform", label: "transform", control: "text", defaultValue: "0, 0, 0" },
        {
          id: "geometry-scale",
          label: "scale",
          control: "number",
          defaultValue: 1,
          min: 0.01,
          step: 0.1,
        },
        {
          id: "geometry-motion",
          label: "motion",
          control: "select",
          defaultValue: "static",
          options: ["static", "animated", "instanced"],
        },
      ],
    },
    {
      title: "Shape",
      settings: [
        {
          id: "geometry-radius",
          label: "radius / extent",
          control: "number",
          defaultValue: 1,
          min: 0,
          step: 0.1,
        },
        {
          id: "geometry-segments",
          label: "segments",
          control: "number",
          defaultValue: 32,
          min: 3,
          step: 1,
        },
        {
          id: "geometry-visible-to-camera",
          label: "visible to camera",
          control: "toggle",
          defaultValue: true,
        },
      ],
    },
  ],
  material: [
    {
      title: "Surface",
      settings: [
        {
          id: "material-base-color",
          label: "base color",
          control: "select",
          defaultValue: "neutral gray",
          options: ["neutral gray", "warm white", "copper", "glass blue", "emissive white"],
        },
        {
          id: "material-roughness",
          label: "roughness",
          control: "number",
          defaultValue: 0.45,
          min: 0,
          max: 1,
          step: 0.01,
        },
        {
          id: "material-metallic",
          label: "metallic",
          control: "number",
          defaultValue: 0,
          min: 0,
          max: 1,
          step: 0.01,
        },
      ],
    },
    {
      title: "Transport",
      settings: [
        {
          id: "material-ior",
          label: "index of refraction",
          control: "number",
          defaultValue: 1.5,
          min: 1,
          step: 0.01,
        },
        {
          id: "material-emission",
          label: "emission strength",
          control: "number",
          defaultValue: 0,
          min: 0,
          step: 0.1,
        },
      ],
    },
  ],
  light: [
    {
      title: "Emission",
      settings: [
        {
          id: "light-intensity",
          label: "intensity",
          control: "number",
          defaultValue: 4,
          min: 0,
          step: 0.1,
        },
        {
          id: "light-color",
          label: "color",
          control: "select",
          defaultValue: "white",
          options: ["white", "warm", "cool", "sky", "custom"],
        },
        {
          id: "light-size",
          label: "size / radius",
          control: "number",
          defaultValue: 1,
          min: 0,
          step: 0.1,
        },
      ],
    },
    {
      title: "Sampling",
      settings: [
        {
          id: "light-samples",
          label: "samples",
          control: "number",
          defaultValue: 1,
          min: 1,
          step: 1,
        },
        { id: "light-cast-shadows", label: "cast shadows", control: "toggle", defaultValue: true },
      ],
    },
  ],
  "scene-loader": [
    {
      title: "Source",
      settings: [
        {
          id: "loader-path",
          label: "asset path",
          control: "text",
          defaultValue: "/scenes/demo.glb",
        },
        {
          id: "loader-units",
          label: "units",
          control: "select",
          defaultValue: "meters",
          options: ["meters", "centimeters", "scene units"],
        },
      ],
    },
    {
      title: "Import",
      settings: [
        {
          id: "loader-generate-normals",
          label: "generate normals",
          control: "toggle",
          defaultValue: false,
        },
        {
          id: "loader-merge-materials",
          label: "merge materials",
          control: "toggle",
          defaultValue: true,
        },
      ],
    },
  ],
  tracer: [
    {
      title: "Acceleration",
      settings: [
        {
          id: "tracer-build-quality",
          label: "build quality",
          control: "select",
          defaultValue: "balanced",
          options: ["fast", "balanced", "high quality"],
        },
        {
          id: "tracer-leaf-size",
          label: "leaf size",
          control: "number",
          defaultValue: 4,
          min: 1,
          step: 1,
        },
        {
          id: "tracer-refit",
          label: "refit dynamic geometry",
          control: "toggle",
          defaultValue: true,
        },
      ],
    },
    {
      title: "Traversal",
      settings: [
        {
          id: "tracer-max-steps",
          label: "max steps",
          control: "number",
          defaultValue: 256,
          min: 1,
          step: 1,
        },
        { id: "tracer-any-hit", label: "any-hit shadows", control: "toggle", defaultValue: true },
      ],
    },
  ],
  sampler: [
    {
      title: "Image Sampling",
      settings: [
        {
          id: "sampler-spp",
          label: "samples per pixel",
          control: "number",
          defaultValue: 1,
          min: 1,
          step: 1,
        },
        {
          id: "sampler-sequence",
          label: "sequence",
          control: "select",
          defaultValue: "per-frame",
          options: ["per-frame", "persistent", "scrambled"],
        },
        { id: "sampler-jitter", label: "pixel jitter", control: "toggle", defaultValue: true },
      ],
    },
    {
      title: "Randomness",
      settings: [
        {
          id: "sampler-seed",
          label: "seed",
          control: "number",
          defaultValue: 1337,
          min: 0,
          step: 1,
        },
        {
          id: "sampler-dimensions",
          label: "dimensions",
          control: "number",
          defaultValue: 8,
          min: 1,
          step: 1,
        },
      ],
    },
  ],
  integrator: [
    {
      title: "Path Limits",
      settings: [
        {
          id: "integrator-max-bounces",
          label: "max bounces",
          control: "number",
          defaultValue: 6,
          min: 0,
          step: 1,
        },
        {
          id: "integrator-min-bounces",
          label: "min bounces",
          control: "number",
          defaultValue: 2,
          min: 0,
          step: 1,
        },
        {
          id: "integrator-russian-roulette",
          label: "russian roulette",
          control: "toggle",
          defaultValue: true,
        },
      ],
    },
    {
      title: "Lighting",
      settings: [
        {
          id: "integrator-nee",
          label: "next-event estimation",
          control: "toggle",
          defaultValue: true,
        },
        {
          id: "integrator-mis",
          label: "multiple importance sampling",
          control: "toggle",
          defaultValue: true,
        },
      ],
    },
  ],
  denoiser: [
    {
      title: "Filter",
      settings: [
        {
          id: "denoiser-strength",
          label: "strength",
          control: "number",
          defaultValue: 0.65,
          min: 0,
          max: 1,
          step: 0.01,
        },
        {
          id: "denoiser-radius",
          label: "radius",
          control: "number",
          defaultValue: 2,
          min: 0,
          step: 1,
        },
        {
          id: "denoiser-temporal",
          label: "temporal history",
          control: "toggle",
          defaultValue: true,
        },
      ],
    },
    {
      title: "Guides",
      settings: [
        { id: "denoiser-depth-guide", label: "depth guide", control: "toggle", defaultValue: true },
        {
          id: "denoiser-normal-guide",
          label: "normal guide",
          control: "toggle",
          defaultValue: true,
        },
        {
          id: "denoiser-albedo-guide",
          label: "albedo guide",
          control: "toggle",
          defaultValue: false,
        },
      ],
    },
  ],
  tonemapper: [
    {
      title: "Exposure",
      settings: [
        {
          id: "tonemapper-exposure",
          label: "exposure",
          control: "number",
          defaultValue: 0,
          step: 0.1,
          suffix: "EV",
        },
        {
          id: "tonemapper-gamma",
          label: "gamma",
          control: "number",
          defaultValue: 2.2,
          min: 0.1,
          step: 0.1,
        },
        {
          id: "tonemapper-white-point",
          label: "white point",
          control: "number",
          defaultValue: 1,
          min: 0.1,
          step: 0.1,
        },
      ],
    },
    {
      title: "Output",
      settings: [
        {
          id: "tonemapper-color-space",
          label: "color space",
          control: "select",
          defaultValue: "sRGB",
          options: ["sRGB", "display P3", "Rec.709", "linear RGB"],
        },
        { id: "tonemapper-dither", label: "dither", control: "toggle", defaultValue: true },
      ],
    },
  ],
  "render-target": [
    {
      title: "Resolution",
      settings: [
        {
          id: "target-resolution",
          label: "resolution",
          control: "select",
          defaultValue: "1280 x 720",
          options: ["800 x 800", "1280 x 720", "1920 x 1080", "custom"],
        },
        {
          id: "target-scale",
          label: "scale",
          control: "number",
          defaultValue: 1,
          min: 0.1,
          max: 2,
          step: 0.1,
        },
      ],
    },
    {
      title: "Accumulation",
      settings: [
        {
          id: "target-progressive",
          label: "progressive accumulation",
          control: "toggle",
          defaultValue: true,
        },
        {
          id: "target-max-samples",
          label: "sample budget",
          control: "number",
          defaultValue: 256,
          min: 1,
          step: 1,
        },
      ],
    },
  ],
  display: [
    {
      title: "Viewport",
      settings: [
        {
          id: "display-fit",
          label: "fit mode",
          control: "select",
          defaultValue: "contain",
          options: ["contain", "cover", "1:1"],
        },
        {
          id: "display-zoom",
          label: "zoom",
          control: "number",
          defaultValue: 1,
          min: 0.1,
          step: 0.1,
        },
      ],
    },
    {
      title: "Overlays",
      settings: [
        {
          id: "display-sample-count",
          label: "sample count",
          control: "toggle",
          defaultValue: true,
        },
        { id: "display-frame-time", label: "frame time", control: "toggle", defaultValue: true },
        {
          id: "display-pixel-inspector",
          label: "pixel inspector",
          control: "toggle",
          defaultValue: false,
        },
      ],
    },
  ],
  "debug-views": [
    {
      title: "Inspection",
      settings: [
        {
          id: "debug-range-min",
          label: "range min",
          control: "number",
          defaultValue: 0,
          step: 0.1,
        },
        {
          id: "debug-range-max",
          label: "range max",
          control: "number",
          defaultValue: 1,
          step: 0.1,
        },
        { id: "debug-normalize", label: "normalize", control: "toggle", defaultValue: true },
      ],
    },
    {
      title: "Overlay",
      settings: [
        {
          id: "debug-opacity",
          label: "opacity",
          control: "number",
          defaultValue: 1,
          min: 0,
          max: 1,
          step: 0.01,
        },
        { id: "debug-legend", label: "legend", control: "toggle", defaultValue: true },
      ],
    },
  ],
};

export function getInitialActiveOptions() {
  return Object.fromEntries(
    pipelineSections.map((section) => [
      section.id,
      section.selectOptions.find((option) => section.minimum.includes(option)) ??
        section.selectOptions[0],
    ]),
  );
}

export function getInitialSettingValues() {
  return Object.fromEntries(
    [
      ...cameraModes.flatMap((mode) => mode.settingGroups),
      ...Object.values(pipelineSectionSettingGroups).flat(),
    ].flatMap((group) => group.settings.map((setting) => [setting.id, setting.defaultValue])),
  );
}
