#ifndef RTR_CAMERA_DEFAULTS_H
#define RTR_CAMERA_DEFAULTS_H

/* Declaration-free camera constants shared by the host and GLSL. */
#define RTR_CAMERA_DEFAULT_YAW 0.35
#define RTR_CAMERA_FOREST_DEFAULT_PITCH 0.18
#define RTR_CAMERA_FOREST_DEFAULT_RADIUS 3.4
#define RTR_CAMERA_FOREST_TARGET_Y 0.45
#define RTR_CAMERA_CASTLE_DEFAULT_PITCH 0.473
#define RTR_CAMERA_CASTLE_DEFAULT_RADIUS 2.35
#define RTR_CAMERA_CASTLE_TARGET_Y -0.12

#endif
