{
  description = "CMake-based build and development shell for realtimerays";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  };

  outputs = { self, nixpkgs, ... }:
    let
      systems = [
        "aarch64-darwin"
        "x86_64-darwin"
      ];

      forAllSystems = nixpkgs.lib.genAttrs systems;
    in
    {
      packages = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          lib = pkgs.lib;

          moltenvkIcd = "${pkgs.moltenvk}/share/vulkan/icd.d/MoltenVK_icd.json";
          vulkanRuntimeLibPath = lib.makeLibraryPath [
            pkgs.vulkan-loader
            pkgs.moltenvk
          ];
        in
        {
          default = pkgs.stdenv.mkDerivation {
            pname = "realtimerays";
            version = "0.1.0";
            src = ./.;

            nativeBuildInputs = [
              pkgs.cmake
              pkgs.ninja
              pkgs.shaderc.bin
              pkgs.makeWrapper
            ];

            buildInputs = [
              pkgs.vulkan-headers
              pkgs.vulkan-loader
              pkgs.moltenvk
              pkgs.apple-sdk
            ];

            cmakeBuildType = "Release";

            postInstall = ''
              wrapProgram "$out/bin/greatbadbeyond" \
                --set-default VK_ICD_FILENAMES ${moltenvkIcd} \
                --prefix DYLD_LIBRARY_PATH : ${vulkanRuntimeLibPath}
            '';

            meta = {
              description = "GLFW-free Vulkan/MoltenVK realtime rays experiment";
              mainProgram = "greatbadbeyond";
              platforms = lib.platforms.darwin;
            };
          };
        });

      apps = forAllSystems (system: {
        default = {
          type = "app";
          program = "${self.packages.${system}.default}/bin/greatbadbeyond";
        };
      });

      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          lib = pkgs.lib;

          moltenvkIcd = "${pkgs.moltenvk}/share/vulkan/icd.d/MoltenVK_icd.json";
          vulkanRuntimeLibPath = lib.makeLibraryPath [
            pkgs.vulkan-loader
            pkgs.moltenvk
          ];
          vulkanSdk = pkgs.symlinkJoin {
            name = "realtimerays-vulkan-sdk";
            paths = [
              pkgs.shaderc.bin
              pkgs.vulkan-headers
              pkgs.vulkan-loader
            ];
          };
        in
        {
          default = pkgs.mkShell {
            inputsFrom = [ self.packages.${system}.default ];

            packages = [
              pkgs.cmake
              pkgs.ninja
              pkgs.pkg-config
              pkgs.shaderc.bin
              pkgs.vulkan-tools
              pkgs.vulkan-validation-layers
              pkgs.zsh
            ];

            shellHook = ''
              export REALTIMERAYS_ROOT="$PWD"
              export VULKAN_SDK=${vulkanSdk}
              export VK_LAYER_PATH=${pkgs.vulkan-validation-layers}/share/vulkan/explicit_layer.d
              export VK_ICD_FILENAMES="''${VK_ICD_FILENAMES:-${moltenvkIcd}}"
              export DYLD_LIBRARY_PATH="${vulkanRuntimeLibPath}:''${DYLD_LIBRARY_PATH:-}"

              export ZDOTDIR="$PWD/.nix-zsh"
              mkdir -p "$ZDOTDIR"
              cat > "$ZDOTDIR/.zshrc" <<'EOF'
              # Generated by flake.nix. Edit flake.nix, not this file.
              if [[ -r "$HOME/.zshrc" && -z "$REALTIMERAYS_NO_USER_ZSHRC" ]]; then
                source "$HOME/.zshrc"
              fi

              alias configure='cmake --preset dev'
              alias build='cmake --build --preset dev'
              alias run='./build/greatbadbeyond'
              alias clean-build='rm -rf build compile_commands.json && cmake --preset dev && cmake --build --preset dev'
              alias nix-build='nix build path:$PWD'
              alias nix-run='nix run path:$PWD'

              realtimerays() {
                local cmd="''${1:-}"
                case "$cmd" in
                  configure) shift; cmake --preset dev "$@" ;;
                  build) shift; cmake --build --preset dev "$@" ;;
                  run) shift; ./build/greatbadbeyond "$@" ;;
                  clean-build) shift; rm -rf build compile_commands.json && cmake --preset dev && cmake --build --preset dev "$@" ;;
                  nix-build) shift; nix build path:$PWD "$@" ;;
                  nix-run) shift; nix run path:$PWD "$@" ;;
                  ""|-h|--help|help)
                    print 'usage: realtimerays <command>'
                    print 'commands: configure build run clean-build nix-build nix-run'
                    ;;
                  *)
                    print -u2 "realtimerays: unknown command: $cmd"
                    return 2
                    ;;
                esac
              }

              echo "realtimerays dev shell"
              echo "  configure: cmake --preset dev"
              echo "  build:     cmake --build --preset dev"
              echo "  run:       ./build/greatbadbeyond"
              EOF

              export SHELL=${pkgs.zsh}/bin/zsh
              case "$-" in
                *i*)
                  if [ -z "''${REALTIMERAYS_IN_ZSH:-}" ]; then
                    export REALTIMERAYS_IN_ZSH=1
                    exec ${pkgs.zsh}/bin/zsh -i
                  fi
                  ;;
              esac
            '';
          };
        });

      formatter = forAllSystems (system:
        let pkgs = import nixpkgs { inherit system; };
        in pkgs.nixpkgs-fmt);
    };
}
