{
  description = "Nix-orchestrated build and development environment for realtimerays";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  };

  outputs = { self, nixpkgs, ... }:
    let
      systems = [
        "aarch64-darwin"
        "x86_64-darwin"
      ];

      forAllSystems = nixpkgs.lib.genAttrs systems;

      perSystem = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          lib = pkgs.lib;

          cc = "${pkgs.stdenv.cc}/bin/cc";
          sdkRoot = pkgs.apple-sdk.sdkroot;
          moltenvkIcd = "${pkgs.moltenvk}/share/vulkan/icd.d/MoltenVK_icd.json";
          vulkanRuntimeLibPath = "${pkgs.vulkan-loader}/lib:${pkgs.moltenvk}/lib";

          vulkanSdk = pkgs.symlinkJoin {
            name = "realtimerays-vulkan-sdk";
            paths = [
              pkgs.shaderc.bin
              pkgs.vulkan-headers
              pkgs.vulkan-loader
            ];
          };

          embedSpv = pkgs.writeText "embed_spv.py" ''
            import pathlib
            import struct
            import sys

            if len(sys.argv) != 4:
                raise SystemExit("usage: embed_spv.py INPUT_FILE OUTPUT_FILE SYMBOL_NAME")

            input_file = pathlib.Path(sys.argv[1])
            output_file = pathlib.Path(sys.argv[2])
            symbol_name = sys.argv[3]
            data = input_file.read_bytes()

            if not data:
                raise SystemExit(f"input SPIR-V file is empty: {input_file}")
            if len(data) % 4 != 0:
                raise SystemExit(f"SPIR-V bytecode size must be a multiple of 4 bytes: {input_file}")

            words = struct.unpack(f"<{len(data) // 4}I", data)
            output_file.parent.mkdir(parents=True, exist_ok=True)

            with output_file.open("w", encoding="utf-8") as out:
                out.write("// Generated by Nix. Do not edit.\n")
                out.write("#pragma once\n\n")
                out.write("#include <stddef.h>\n")
                out.write("#include <stdint.h>\n\n")
                out.write(f"static const uint32_t {symbol_name}[] = {{\n")
                for index in range(0, len(words), 8):
                    chunk = words[index:index + 8]
                    suffix = "," if index + 8 < len(words) else ""
                    out.write("    " + ", ".join(f"0x{word:08x}u" for word in chunk) + suffix + "\n")
                out.write("};\n")
                out.write(f"static const size_t {symbol_name}_size = sizeof({symbol_name});\n")
          '';

          generateShaders = pkgs.writeShellApplication {
            name = "realtimerays-generate-shaders";
            runtimeInputs = [
              pkgs.python3
              pkgs.shaderc.bin
            ];
            text = ''
              root="''${1:-$PWD}"
              shader_dir="$root/build/generated/shaders"

              mkdir -p "$shader_dir"
              glslc "$root/resources/shaders/gradient.comp" -o "$shader_dir/gradient.comp.spv"
              python3 ${embedSpv} "$shader_dir/gradient.comp.spv" "$shader_dir/gradient_comp_spv.h" gradientCompSpv
            '';
          };

          compileCommands = pkgs.writeShellApplication {
            name = "realtimerays-compile-commands";
            runtimeInputs = [
              generateShaders
              pkgs.python3
            ];
            text = ''
              root="''${1:-$PWD}"

              realtimerays-generate-shaders "$root" >/dev/null

              python3 - "$root" <<'PY'
            import json
            import os
            import pathlib
            import shlex
            import sys

            root = pathlib.Path(sys.argv[1]).resolve()
            compiler = os.environ.get("CC", "${cc}")
            build = root / "build"
            generated = build / "generated" / "shaders"
            obj = build / "obj"

            common_flags = [
                "-Wall",
                "-Wextra",
                "-Wpedantic",
                f"-I{generated}",
                "-I${pkgs.vulkan-headers}/include",
                "-isysroot",
                "${sdkRoot}",
            ]

            entries = []
            for source, output, extra_flags in [
                (root / "src" / "main.c", obj / "main.o", ["-std=c11"]),
                (root / "src" / "macos_platform.m", obj / "macos_platform.o", ["-x", "objective-c"]),
            ]:
                args = [compiler, *extra_flags, *common_flags, "-c", str(source), "-o", str(output)]
                entries.append({
                    "directory": str(root),
                    "file": str(source),
                    "output": str(output),
                    "arguments": args,
                    "command": shlex.join(args),
                })

            (root / "compile_commands.json").write_text(json.dumps(entries, indent=2) + "\n", encoding="utf-8")
            PY

              echo "wrote $root/compile_commands.json"
            '';
          };

          localBuild = pkgs.writeShellApplication {
            name = "realtimerays-build";
            runtimeInputs = [
              generateShaders
              compileCommands
              pkgs.shaderc.bin
              pkgs.python3
            ];
            text = ''
              root="''${1:-$PWD}"
              build_dir="$root/build"
              obj_dir="$build_dir/obj"
              shader_dir="$build_dir/generated/shaders"
              compiler="''${CC:-${cc}}"

              export SDKROOT=${sdkRoot}
              export VULKAN_SDK=${vulkanSdk}
              export VK_ICD_FILENAMES="''${VK_ICD_FILENAMES:-${moltenvkIcd}}"
              export DYLD_LIBRARY_PATH="${vulkanRuntimeLibPath}:''${DYLD_LIBRARY_PATH:-}"

              mkdir -p "$obj_dir"
              realtimerays-compile-commands "$root"

              common_flags=(
                -Wall
                -Wextra
                -Wpedantic
                -I"$shader_dir"
                -I${pkgs.vulkan-headers}/include
                -isysroot ${sdkRoot}
              )

              "$compiler" -std=c11 "''${common_flags[@]}" -c "$root/src/main.c" -o "$obj_dir/main.o"
              "$compiler" -x objective-c "''${common_flags[@]}" -c "$root/src/macos_platform.m" -o "$obj_dir/macos_platform.o"
              "$compiler" "$obj_dir/main.o" "$obj_dir/macos_platform.o" \
                -L${pkgs.vulkan-loader}/lib \
                -lvulkan \
                -framework AppKit \
                -framework QuartzCore \
                -o "$build_dir/greatbadbeyond"

              echo "built $build_dir/greatbadbeyond"
            '';
          };

          projectZshrc = pkgs.writeText "realtimerays-zshrc" ''
            # Nix-managed project zsh config.
            autoload -Uz colors && colors
            setopt auto_cd interactive_comments prompt_subst
            bindkey -e

            unset CMAKE_GENERATOR
            export REALTIMERAYS_ROOT="''${REALTIMERAYS_ROOT:-$PWD}"

            alias gen-shaders='realtimerays-generate-shaders'
            alias compile-commands='realtimerays-compile-commands'
            alias build='realtimerays-build'
            alias run='realtimerays-build && ./build/greatbadbeyond'
            alias nix-build='nix build path:$PWD'
            alias nix-run='nix run path:$PWD'
            alias clean-build='rm -rf build && realtimerays-build'

            PROMPT='%F{cyan}realtimerays%f %F{yellow}%~%f %# '
          '';
        in
        {
          packages = {
            default = pkgs.stdenv.mkDerivation {
              pname = "realtimerays";
              version = "0.1.0";
              src = ./.;

              nativeBuildInputs = [
                generateShaders
                pkgs.shaderc.bin
                pkgs.python3
              ];

              buildInputs = [
                pkgs.vulkan-headers
                pkgs.vulkan-loader
                pkgs.moltenvk
                pkgs.apple-sdk
              ];

              dontConfigure = true;

              buildPhase = ''
                runHook preBuild

                mkdir -p build/obj
                realtimerays-generate-shaders "$PWD"

                common_flags=(
                  -Wall
                  -Wextra
                  -Wpedantic
                  -I"$PWD/build/generated/shaders"
                  -I${pkgs.vulkan-headers}/include
                  -isysroot ${sdkRoot}
                )

                ${cc} -std=c11 "''${common_flags[@]}" -c src/main.c -o build/obj/main.o
                ${cc} -x objective-c "''${common_flags[@]}" -c src/macos_platform.m -o build/obj/macos_platform.o
                ${cc} build/obj/main.o build/obj/macos_platform.o \
                  -L${pkgs.vulkan-loader}/lib \
                  -lvulkan \
                  -framework AppKit \
                  -framework QuartzCore \
                  -o build/greatbadbeyond

                runHook postBuild
              '';

              installPhase = ''
                runHook preInstall

                mkdir -p $out/bin $out/libexec
                cp build/greatbadbeyond $out/libexec/greatbadbeyond

                cat > $out/bin/greatbadbeyond <<EOF
                #!/bin/sh
                export VK_ICD_FILENAMES="\''${VK_ICD_FILENAMES:-${moltenvkIcd}}"
                export DYLD_LIBRARY_PATH="${vulkanRuntimeLibPath}:\''${DYLD_LIBRARY_PATH:-}"
                exec "$out/libexec/greatbadbeyond" "\$@"
                EOF
                chmod +x $out/bin/greatbadbeyond

                runHook postInstall
              '';

              meta = {
                description = "GLFW-free Vulkan/MoltenVK realtime rays experiment";
                mainProgram = "greatbadbeyond";
                platforms = lib.platforms.darwin;
              };
            };

            build-local = localBuild;
            compile-commands = compileCommands;
            generate-shaders = generateShaders;
          };

          apps = {
            default = {
              type = "app";
              program = "${self.packages.${system}.default}/bin/greatbadbeyond";
            };
            build = {
              type = "app";
              program = "${localBuild}/bin/realtimerays-build";
            };
            compile-commands = {
              type = "app";
              program = "${compileCommands}/bin/realtimerays-compile-commands";
            };
            generate-shaders = {
              type = "app";
              program = "${generateShaders}/bin/realtimerays-generate-shaders";
            };
          };

          devShells.default = pkgs.mkShell {
            packages = [
              localBuild
              compileCommands
              generateShaders
              pkgs.pkg-config
              pkgs.shaderc.bin
              pkgs.vulkan-headers
              pkgs.vulkan-loader
              pkgs.vulkan-tools
              pkgs.vulkan-validation-layers
              pkgs.moltenvk
              pkgs.apple-sdk
              pkgs.zsh
            ];

            shellHook = ''
              export REALTIMERAYS_ROOT="$PWD"
              export VULKAN_SDK=${vulkanSdk}
              export CC="''${CC:-${cc}}"
              export SDKROOT=${sdkRoot}
              export VK_LAYER_PATH=${pkgs.vulkan-validation-layers}/share/vulkan/explicit_layer.d
              export VK_ICD_FILENAMES="''${VK_ICD_FILENAMES:-${moltenvkIcd}}"
              export DYLD_LIBRARY_PATH="${vulkanRuntimeLibPath}:''${DYLD_LIBRARY_PATH:-}"

              realtimerays-compile-commands "$PWD" >/dev/null

              export ZDOTDIR="$PWD/.nix-zsh"
              mkdir -p "$ZDOTDIR"
              cat > "$ZDOTDIR/.zshrc" <<EOF
# Generated by flake.nix. Edit flake.nix, not this file.
if [[ -r "\$HOME/.zshrc" && -z "''${REALTIMERAYS_NO_USER_ZSHRC:-}" ]]; then
  source "\$HOME/.zshrc"
fi
source ${projectZshrc}
EOF

              export SHELL=${pkgs.zsh}/bin/zsh
              case "$-" in
                *i*)
                  if [ -z "''${REALTIMERAYS_IN_ZSH:-}" ]; then
                    export REALTIMERAYS_IN_ZSH=1
                    exec ${pkgs.zsh}/bin/zsh -i
                  fi
                  ;;
              esac
            '';
          };
        });
    in
    {
      packages = forAllSystems (system: perSystem.${system}.packages);
      apps = forAllSystems (system: perSystem.${system}.apps);
      devShells = forAllSystems (system: perSystem.${system}.devShells);
      formatter = forAllSystems (system:
        let pkgs = import nixpkgs { inherit system; };
        in pkgs.nixpkgs-fmt);
    };
}
