if(NOT DEFINED INPUT_FILE)
    message(FATAL_ERROR "INPUT_FILE is required")
endif()

if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required")
endif()

if(NOT DEFINED SYMBOL_NAME)
    message(FATAL_ERROR "SYMBOL_NAME is required")
endif()

if(NOT EXISTS "${INPUT_FILE}")
    message(FATAL_ERROR "Input SPIR-V file not found: ${INPUT_FILE}")
endif()

file(READ "${INPUT_FILE}" shaderHex HEX)
string(LENGTH "${shaderHex}" shaderHexLength)

if(shaderHexLength EQUAL 0)
    message(FATAL_ERROR "Input SPIR-V file is empty: ${INPUT_FILE}")
endif()

math(EXPR shaderHexRemainder "${shaderHexLength} % 8")
if(NOT shaderHexRemainder EQUAL 0)
    message(FATAL_ERROR "SPIR-V bytecode size must be a multiple of 4 bytes: ${INPUT_FILE}")
endif()

math(EXPR shaderWordCount "${shaderHexLength}/8")
math(EXPR lastWordIndex "${shaderWordCount} - 1")

set(outputText "// Generated by cmake/embed_spv.cmake. Do not edit.\n")
string(APPEND outputText "#pragma once\n\n")
string(APPEND outputText "#include <stddef.h>\n")
string(APPEND outputText "#include <stdint.h>\n\n")
string(APPEND outputText "static const uint32_t ${SYMBOL_NAME}[] = {\n")

set(wordsOnLine 0)
foreach(wordIndex RANGE 0 ${lastWordIndex})
    math(EXPR hexIndex "${wordIndex}*8")
    string(SUBSTRING "${shaderHex}" ${hexIndex} 2 b0)
    math(EXPR hexIndex "${hexIndex}+2")
    string(SUBSTRING "${shaderHex}" ${hexIndex} 2 b1)
    math(EXPR hexIndex "${hexIndex}+2")
    string(SUBSTRING "${shaderHex}" ${hexIndex} 2 b2)
    math(EXPR hexIndex "${hexIndex}+2")
    string(SUBSTRING "${shaderHex}" ${hexIndex} 2 b3)

    string(APPEND outputText "0x${b3}${b2}${b1}${b0}u")

    if(NOT wordIndex EQUAL lastWordIndex)
        string(APPEND outputText ", ")
    endif()

    math(EXPR wordsOnLine "${wordsOnLine} + 1")
    if(wordsOnLine EQUAL 8)
        string(APPEND outputText "\n")
        set(wordsOnLine 0)
    endif()
endforeach()

if(NOT wordsOnLine EQUAL 0)
    string(APPEND outputText "\n")
endif()

string(APPEND outputText "};\n")
string(APPEND outputText "static const size_t ${SYMBOL_NAME}_size = sizeof(${SYMBOL_NAME});\n")

file(WRITE "${OUTPUT_FILE}" "${outputText}")
